### ISSUE TITLE
debian下打包失败。

### ISSUE THREAD

**Issue by winezer0** [zsdevX/DarkEye#1]
debian下打包失败。
麻烦上传一个下载地址，目前的下载地址我们没有权限访问

**Comment by zsdevX** [comment]
更新代码后 试试这样编译
qtdeploy  -uic=false build linux

**Comment by winezer0** [comment]
zsdevX，感谢你的回复，&nbsp;我发现你已经在github上传可执行文件了，我就直接下载了。大的golang项目对于我来说还是有些复杂了，配置过于复杂




------------------&nbsp;Original&nbsp;------------------
