### ISSUE TITLE
exe无法生成结果

### ISSUE THREAD

**Issue by xiaozhao66** [zsdevX/DarkEye#2]
使用zoomeye 查询结果显示 The filename, directory name, or volume label syntax is incorrect.
系统为win10 1809 给了管理员权限

**Comment by zsdevX** [comment]
> 使用zoomeye 查询结果显示 The filename, directory name, or volume label syntax is incorrect.
> 系统为win10 1809 给了管理员权限

师傅方便贴下**搜索**的内容 敏感的部分打个码就行。 我初步怀疑和中文或特殊字符有关。工具会把搜索的内容作为文件名。
如果是这个问题我调整下代码

**Comment by zsdevX** [comment]
问题已经复现：
因中文导致保存文件失败。 已经修复。
