### ISSUE TITLE
无法指定端口扫描

### ISSUE THREAD

**Issue by wpf97** [zsdevX/DarkEye#3]
比如我只想扫描c段的80，
./superscan_darwin_amd64 -ip 192.168.233.1-192.168.233.254 -port-list 80
无法扫到80端口

**Comment by zsdevX** [comment]
> 比如我只想扫描c段的80，
> ./superscan_darwin_amd64 -ip 192.168.233.1-192.168.233.254 -port-list 80
> 无法扫到80端口

有提示报什么错误或提示吗 我验证了下 正常情况下是可以的。是不是超时引起的？

![Uploading image.png…]()

**Comment by wpf97** [comment]
感谢，今天又测试了一样，没问题

**Comment by zsdevX** [comment]
> 感谢，今天又测试了一样，没问题

师傅的意思是问题还是存在 不能选端口吗

**Comment by zsdevX** [comment]
问题不存在
