### ISSUE TITLE
是否可以在 release 提供打包好的可执行文件

### ISSUE THREAD

**Issue by No-Github** [zsdevX/DarkEye#5]
请问下是否方便在 release 中提供打包好的可执行文件
如果担心速度问题，可以采用 jsdeliv 做CDN加速，天翼云盘的文件不便于集成到下载脚本中

**Comment by zsdevX** [comment]
：）
https://github.com/zsdevX/DarkEye/releases/download/3.1/superscan_darwin_amd64
