### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by cfan6** [zsdevX/DarkEye#6]
ubuntu 20.04
编译好freerdp
root@root:~/Desktop/compile$ path=/home/root/Desktop/compile
root@root:~/Desktop/compile$ export CGO_CFLAGS="-I${path}/include/freerdp3 -I${path}/include/winpr3 -DRDP_SUPPORT -static"
root@root:~/Desktop/compile$ export CGO_LDFLAGS="${path}/lib/libfreerdp3.a $path/lib/libwinpr3.a $path/lib/libfreerdp-client3.a $path/libssl.a $path/libcrypto.a"
root@root:~/Desktop/compile$ go build main.go 
错误信息：
# command-line-arguments
/usr/bin/ld: ./lib/libfreerdp3.a(h264_ffmpeg.c.o): in function `libavcodec_decompress':
h264_ffmpeg.c:(.text+0x2d): undefined reference to `av_init_packet'
/usr/bin/ld: h264_ffmpeg.c:(.text+0x44): undefined reference to `avcodec_send_packet'
/usr/bin/ld: h264_ffmpeg.c:(.text+0x6b): undefined reference to `avcodec_receive_frame'
/usr/bin/ld: ./lib/libfreerdp3.a(h264_ffmpeg.c.o): in function `libavcodec_uninit':
h264_ffmpeg.c:(.text+0x1a2): undefined reference to `av_frame_free'
/usr/bin/ld: h264_ffmpeg.c:(.text+0x1b1): undefined reference to `av_parser_close'
/usr/bin/ld: h264_ffmpeg.c:(.text+0x1c0): undefined reference to `avcodec_close'
/usr/bin/ld: h264_ffmpeg.c:(.text+0x1ca): undefined reference to `avcodec_free_context'
/usr/bin/ld: h264_ffmpeg.c:(.text+0x1e9): undefined reference to `avcodec_close'
/usr/bin/ld: h264_ffmpeg.c:(.text+0x1f2): undefined reference to `avcodec_free_context'
/usr/bin/ld: ./lib/libfreerdp3.a(h264_ffmpeg.c.o): in function `libavcodec_init':

这是什么情况？

另：
我在alpine docker镜像编译没问题，但是编译出来的文件无法在ubuntu上运行。

**Comment by zsdevX** [comment]
试试go build -a xxxx.go

**Comment by cfan6** [comment]
@zsdevX 
报一样的错误，明天试试centos

**Comment by zsdevX** [comment]
> @zsdevX
> 报一样的错误，明天试试centos

freerdp试试用系统自带的库， 自己编译的可能会有问题。

**Comment by cfan6** [comment]
用alpine能编译通过，但在不同版linux上也不能运行，所以用golang内嵌freerdp打包也不能实现跨平台运行，如果有纯go语言写的rdp包就好了。

**Comment by zsdevX** [comment]
rdp在那时不支持 其它平台  :(
